#ifndef LIBPIXYUSB2_GLOBAL_H
#define LIBPIXYUSB2_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBPIXYUSB2_LIBRARY)
#  define LIBPIXYUSB2SHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBPIXYUSB2SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBPIXYUSB2_GLOBAL_H
